### ISSUE TITLE
New toasts/alert/notification library

### ISSUE THREAD

**Issue by statebait** [shadxx7/elections-frontend#5]
react-s-alert has been discontinued, as such we would like to move to a more active library like [react-toastify](https://github.com/fkhadra/react-toastify).

Solving this issue would require rewriting all toasts/alert/notification code written using the react-s-alert to the new libraries API (react-toastify).

**Comment by sergeycw** [comment]
hi! let me do it!

**Comment by pcube99** [comment]
Is this issue still up?
I would like to contribute to it.

**Comment by statebait** [comment]
Great! I'll assign you to it.

**Comment by pcube99** [comment]
I have tried to clone the repo and run it in local, but because of backend error after login page not loading. What should I do ?

**Comment by pcube99** [comment]
It says, not able to find MongoDB URI.

**Comment by pcube99** [comment]
Can you provide me, backend .env file ?
I am not able to run without it.

**Comment by statebait** [comment]
Hey, I'll update the README of the backend with appropriate instructions. Sorry for the inconvenience.

**Comment by statebait** [comment]
@pcube99 I have now updated the README in https://github.com/gauravsofat/elections-api with appropriate development instructions. Do comment here if you run into problems :)

**Comment by pcube99** [comment]
I have created PR. #7 
Please have a look.

**Comment by statebait** [comment]
#7 fixes this.
